# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# -- Start Aliases -- #
# Most Used
alias c='clear && ls'
alias cls='clear'
alias up='sudo apt update && sudo apt upgrade && sudo apt autoremove && sudo apt autoclean && echo done'
alias la='ls -a'
alias poweroff='sudo poweroff'
alias reboot='echo "Disabled for Toughbook, powering off instead." && sudo poweroff' #used for my toughbook
#alias reboot='sudo reboot' #used for everything else, allowing non-root to shutdown is for losers
alias pg='ping 8.8.8.8'
alias ip='hostname -I'
alias get='sudo apt install'
alias update='sudo apt update'
alias upgrade='sudo apt upgrade'
alias remove='sudo apt autoremove'
alias search='apt search'

# Less Used
alias help='man builtins'
alias games='echo adventure, arithmetic, atc, backgammon, battlestar, bcd, boggle, caesar, canfield, countmail, cribbage, dab, go-fish, gomoku, hack, hangman, hunt, mille, monop, morse, number, pig, phantasia, pom, ppt, primes, quiz, random, rain, robots, rot13, sail, snake, tetris, trek, wargames, worm, worms, wump, wtf'
alias search2='apropos'
alias worms='worms -d 45' #see bsdgames
alias ddg='w3m https://www.duckduckgo.com/html'
alias ssh-on='sudo /etc/init.d/ssh start'
alias ssh-off='sudo /etc/init.d/ssh stop'
alias tor-on='sudo /etc/init.d/tor start'
alias tor-off='sudo /etc/init.d/tor stop'
alias install='dkpg -i'
alias wlan='sudo nano /etc/network/interfaces'
alias wlan2='sudo /etc/init.d/networking restart'
alias pandora='pithos'
#alias pandora2='pianobar' #doesnt work, RIP
#alias disabletrackpad='xinput set-prop 10 "Device Enabled" 0' #used for my thinkpads
alias e='espeak -s 130 '
alias whosup='nmap -sn 192.168.1.1-255' #checks what computers on on the LAN (all my routers are 192.168.1.*)
alias vlc2='vlc --qt-minimal-view --no-qt-system-tray' #works well with tiling window managers
alias sc='neofetch --cpu_temp on && vrms | grep non-free && scrot -d 2'
alias wiki='wikipedia2text -d w3m'

# -- End Aliases -- #

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
