~/.fehbg
while true
do
	LOCALTIME=$(date +\[%Y-%m-%d\]\ \[%H:%M\])
	IP=$(for i in `ip r`; do echo $i; done | grep -A 1 src | tail -n1) # can get confused if you use vmware
	TEMP="$(($(cat /sys/class/thermal/thermal_zone1/temp) / 1000))C"

	if acpi -a | grep off-line > /dev/null
	then
		BAT="[Bat: $(acpi | batlvl)]"
		xsetroot -name "[$IP] $BAT [$TEMP] $LOCALTIME"
	else
		xsetroot -name "[$IP] [$TEMP] $LOCALTIME"
	fi
	sleep 20s
done &

exec dwm
